asttokens==2.0.5
astunparse==1.6.3
backcall==0.2.0
bleach==5.0.0
CacheControl==0.12.11
cachetools==5.0.0
certifi==2021.10.8
charset-normalizer==2.0.12
click==8.1.3
cloudpickle==2.0.0
colorama==0.4.4
commonmark==0.9.1
cycler==0.11.0
Cython==0.29.28
dask==2022.4.2
dask-mpi==2022.4.0
decorator==5.1.1
distributed==2022.4.2
docutils==0.18.1
executing==0.8.3
flatbuffers==2.0
fonttools==4.33.3
fsspec==2022.3.0
gast==0.5.3
google-auth==2.6.6
google-auth-oauthlib==0.4.6
google-pasta==0.2.0
grpcio==1.44.0
h5py==3.6.0
hdmedians==0.14.2
HeapDict==1.0.1
idna==3.3
importlib-metadata==4.11.3
ipython==8.3.0
jedi==0.18.1
Jinja2==3.1.2
joblib==1.1.0
keras==2.8.0
Keras-Preprocessing==1.1.2
keyring==23.5.0
kiwisolver==1.4.2
libclang==14.0.1
locket==1.0.0
lockfile==0.12.2
Markdown==3.3.6
mpi4py==3.1.3
MarkupSafe==2.1.1
matplotlib==3.5.1
matplotlib-inline==0.1.3
msgpack==1.0.3
natsort==8.1.0
numpy==1.22.3
oauthlib==3.2.0
opt-einsum==3.3.0
packaging==21.3
pandas==1.4.2
parso==0.8.3
partd==1.2.0
peptides==0.2.1
pickleshare==0.7.5
Pillow==9.1.0
pkginfo==1.8.2
prompt-toolkit==3.0.29
protobuf==3.20.1
psutil==5.9.0
pure-eval==0.2.2
pyasn1==0.4.8
pyasn1-modules==0.2.8
Pygments==2.12.0
pyparsing==3.0.8
python-dateutil==2.8.2
pytz==2022.1
pywin32-ctypes==0.2.0
PyYAML==6.0
readme-renderer==35.0
requests==2.27.1
requests-oauthlib==1.3.1
requests-toolbelt==0.9.1
rfc3986==2.0.0
rich==12.3.0
rsa==4.8
scikit-bio==0.5.7
scikit-learn==1.0.2
scipy==1.8.0
seqprops==1.0.1
six==1.16.0
sortedcontainers==2.4.0
stack-data==0.2.0
tblib==1.7.0
tensorboard==2.8.0
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.8.1
tensorflow==2.8.0
tensorflow-io-gcs-filesystem==0.25.0
termcolor==1.1.0
tf-estimator-nightly==2.8.0.dev2021122109
threadpoolctl==3.1.0
toolz==0.11.2
tornado==6.1
traitlets==5.1.1
twine==4.0.0
typing_extensions==4.2.0
urllib3==1.26.9
wcwidth==0.2.5
webencodings==0.5.1
Werkzeug==2.1.2
wincertstore==0.2
wrapt==1.14.0
zict==2.2.0
zipp==3.8.0
